"""KataGo analysis-engine wrapper.

Speaks KataGo's line-oriented JSON analysis protocol over a long-lived child
process.  Keeping one process alive matters a lot here: model load plus OpenCL
warm-up costs seconds, which would otherwise be paid on every single move.
"""

from __future__ import annotations

import dataclasses
import json
import os
import queue
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Optional

from .vision import BLACK, WHITE, rc_to_gtp

DEFAULT_CONFIG = """\
# Minimal KataGo analysis config generated by GoEye.
logDir = {log_dir}
logAllRequests = false
logAllResponses = false
logSearchInfo = false
logToStderr = false

# One request at a time is all a live-overlay ever needs.
numAnalysisThreads = 1
numSearchThreads = {search_threads}

nnMaxBatchSize = {batch_size}
nnCacheSizePowerOfTwo = 19
nnMutexPoolSizePowerOfTwo = 15
numNNServerThreadsPerModel = 1

nnBackend = {nn_backend}
openclUseAllDevices = false

# Winrates relative to whoever is to move; the UI converts when it needs to.
reportAnalysisWinratesAs = SIDETOMOVE

# Deterministic output makes the overlay stop flickering between equal moves.
analysisPVLen = 12
rootSymmetryPruning = true
"""


@dataclasses.dataclass
class MoveSuggestion:
    move: str  # GTP coordinate, or "pass"
    winrate: float  # 0..1 for the side to move
    score_lead: float  # points, positive = good for side to move
    visits: int
    prior: float
    pv: list[str]
    order: int


@dataclasses.dataclass
class AnalysisResult:
    side_to_move: str  # "B" or "W"
    moves: list[MoveSuggestion]
    root_winrate: float
    root_score_lead: float
    visits: int
    elapsed: float

    @property
    def best(self) -> Optional[MoveSuggestion]:
        return self.moves[0] if self.moves else None


class EngineError(RuntimeError):
    pass


class KataGoEngine:
    """Long-lived ``katago analysis`` subprocess."""

    def __init__(
        self,
        katago_path: str,
        model_path: "str | list[str]",
        config_path: Optional[str] = None,
        work_dir: Optional[str] = None,
        search_threads: int = 4,
        batch_size: int = 8,
    ) -> None:
        self.katago_path = katago_path
        if isinstance(model_path, str):
            model_path = [model_path]
        self.model_paths = [p for p in model_path if p]
        self.model_path: Optional[str] = None
        self._work_dir = Path(work_dir or Path.home() / ".goeye")
        self._work_dir.mkdir(parents=True, exist_ok=True)

        self._config_path = config_path
        self._search_threads = search_threads
        self._batch_size = batch_size

        self._proc: Optional[subprocess.Popen] = None
        self._responses: "queue.Queue[dict]" = queue.Queue()
        self._pending: dict[str, queue.Queue] = {}
        self._lock = threading.Lock()
        self._counter = 0
        self._stderr_tail: list[str] = []
        self._ready = threading.Event()
        self.backend: str = ""

    # -- lifecycle ---------------------------------------------------------

    def _write_default_config(
        self, search_threads: int, batch_size: int, nn_backend: str = "opencl"
    ) -> Path:
        log_dir = self._work_dir / "logs"
        log_dir.mkdir(parents=True, exist_ok=True)
        path = self._work_dir / f"analysis-{nn_backend}.cfg"
        path.write_text(
            DEFAULT_CONFIG.format(
                log_dir=log_dir,
                search_threads=search_threads,
                batch_size=batch_size,
                nn_backend=nn_backend,
            ),
            encoding="utf-8",
        )
        return path

    def start(self, timeout: float = 300.0) -> None:
        """Launch the engine and block until it answers a probe query.

        Tries each candidate model, and for each model tries OpenCL first then
        a pure-CPU (eigen) backend.  This keeps the app usable on machines
        whose graphics drivers refuse to expose a usable OpenCL device.
        """
        if self._proc is not None:
            return
        if not self.model_paths:
            raise EngineError("no model weights available")

        last_error = ""
        # Metal is the backend KataGo uses on macOS; OpenCL then a pure-CPU
        # (eigen) fallback keeps things working where Metal/OpenCL are absent.
        for model_path in self.model_paths:
            for nn_backend in ("metal", "opencl", "eigen"):
                try:
                    self._launch_one(model_path, nn_backend, timeout)
                    self.model_path = model_path
                    self._ready.set()
                    return
                except EngineError as exc:
                    last_error = str(exc)
                    # tear down a half-started process before retrying
                    self._teardown_proc()
                    continue
        raise EngineError(last_error)

    def _launch_one(self, model_path: str, nn_backend: str, timeout: float) -> None:
        config_path = self._config_path or self._write_default_config(
            self._search_threads, self._batch_size, nn_backend
        )
        self.backend = "GPU" if nn_backend == "opencl" else "CPU"
        cmd = [
            self.katago_path,
            "analysis",
            "-model",
            model_path,
            "-config",
            config_path,
        ]
        self._proc = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
        )
        threading.Thread(target=self._pump_stdout, daemon=True).start()
        threading.Thread(target=self._pump_stderr, daemon=True).start()

        # Probe with a trivial position so callers know when the net is warm.
        probe = self.analyze([], "B", max_visits=2, timeout=timeout)
        if probe is None:
            raise EngineError(
                f"model {model_path} ({nn_backend}) did not respond.\n"
                + "\n".join(self._stderr_tail[-15:])
            )

    def _teardown_proc(self) -> None:
        if self._proc is None:
            return
        try:
            if self._proc.stdin:
                self._proc.stdin.close()
            self._proc.terminate()
            self._proc.wait(timeout=5)
        except Exception:
            try:
                self._proc.kill()
            except Exception:
                pass
        self._proc = None

    def _pump_stdout(self) -> None:
        assert self._proc and self._proc.stdout
        for line in self._proc.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            rid = payload.get("id")
            with self._lock:
                slot = self._pending.pop(rid, None)
            if slot is not None:
                slot.put(payload)

    def _pump_stderr(self) -> None:
        assert self._proc and self._proc.stderr
        for line in self._proc.stderr:
            line = line.rstrip()
            if line:
                self._stderr_tail.append(line)
                del self._stderr_tail[:-200]

    def stop(self) -> None:
        if self._proc is None:
            return
        try:
            if self._proc.stdin:
                self._proc.stdin.close()
            self._proc.terminate()
            self._proc.wait(timeout=5)
        except Exception:
            try:
                self._proc.kill()
            except Exception:
                pass
        self._proc = None
        self._ready.clear()

    @property
    def running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    # -- querying ----------------------------------------------------------

    def analyze(
        self,
        stones: list[tuple[str, str]],
        side_to_move: str,
        komi: float = 7.5,
        rules: str = "chinese",
        board_size: int = 19,
        max_visits: int = 300,
        timeout: float = 30.0,
    ) -> Optional[AnalysisResult]:
        """Analyse a static position.

        ``stones`` is a list of ``("B"|"W", "Q16")`` pairs.  We feed them as
        ``initialStones`` rather than a move list because a screenshot gives us
        a position, not a game record.
        """
        if not self.running:
            raise EngineError("engine is not running")

        with self._lock:
            self._counter += 1
            rid = f"q{self._counter}"
            slot: "queue.Queue[dict]" = queue.Queue(maxsize=1)
            self._pending[rid] = slot

        request = {
            "id": rid,
            "initialStones": [list(s) for s in stones],
            "moves": [],
            "initialPlayer": side_to_move,
            "rules": rules,
            "komi": komi,
            "boardXSize": board_size,
            "boardYSize": board_size,
            "maxVisits": max_visits,
            "includeOwnership": False,
            "includePolicy": False,
        }

        started = time.time()
        assert self._proc and self._proc.stdin
        try:
            self._proc.stdin.write(json.dumps(request) + "\n")
            self._proc.stdin.flush()
        except (BrokenPipeError, ValueError) as exc:
            raise EngineError(f"engine pipe closed: {exc}") from exc

        try:
            payload = slot.get(timeout=timeout)
        except queue.Empty:
            with self._lock:
                self._pending.pop(rid, None)
            return None

        if "error" in payload:
            raise EngineError(str(payload["error"]))

        return self._parse(payload, side_to_move, time.time() - started)

    @staticmethod
    def _parse(payload: dict, side_to_move: str, elapsed: float) -> AnalysisResult:
        infos = payload.get("moveInfos", []) or []
        suggestions = [
            MoveSuggestion(
                move=info.get("move", "pass"),
                winrate=float(info.get("winrate", 0.0)),
                score_lead=float(info.get("scoreLead", 0.0)),
                visits=int(info.get("visits", 0)),
                prior=float(info.get("prior", 0.0)),
                pv=list(info.get("pv", []) or []),
                order=int(info.get("order", 0)),
            )
            for info in infos
        ]
        suggestions.sort(key=lambda m: (m.order, -m.visits))

        root = payload.get("rootInfo", {}) or {}
        return AnalysisResult(
            side_to_move=side_to_move,
            moves=suggestions,
            root_winrate=float(root.get("winrate", 0.0)),
            root_score_lead=float(root.get("scoreLead", 0.0)),
            visits=int(root.get("visits", 0)),
            elapsed=elapsed,
        )


def stones_from_array(stones_array) -> list[tuple[str, str]]:
    """Convert a ``(size, size)`` label array into KataGo ``initialStones``."""
    out: list[tuple[str, str]] = []
    size = stones_array.shape[0]
    for row in range(size):
        for col in range(size):
            value = int(stones_array[row, col])
            if value == BLACK:
                out.append(("B", rc_to_gtp(row, col, size)))
            elif value == WHITE:
                out.append(("W", rc_to_gtp(row, col, size)))
    return out


# ---------------------------------------------------------------------------
# Engine discovery
# ---------------------------------------------------------------------------

def _resolve(candidate: Optional[str]) -> Optional[str]:
    """Resolve a candidate binary name/path to an executable, or ``None``."""
    if not candidate:
        return None
    if os.path.isabs(candidate):
        return candidate if (os.path.isfile(candidate) and os.access(candidate, os.X_OK)) else None
    return shutil.which(candidate)


def find_katago(explicit: Optional[str] = None) -> Optional[str]:
    """Locate a usable ``katago`` binary (explicit path wins, then PATH / common bins)."""
    for candidate in (
        ([explicit] if explicit else [])
        + ["katago", os.path.expanduser("~/go/bin/katago"),
           "/opt/homebrew/bin/katago", "/usr/local/bin/katago", "/usr/bin/katago"]
    ):
        found = _resolve(candidate)
        if found:
            return found
    return None


def find_gnugo(explicit: Optional[str] = None) -> Optional[str]:
    """Locate a usable ``gnugo`` binary as a lightweight fallback engine."""
    for candidate in (
        ([explicit] if explicit else [])
        + ["gnugo", "/opt/homebrew/bin/gnugo", "/usr/local/bin/gnugo", "/usr/bin/gnugo"]
    ):
        found = _resolve(candidate)
        if found:
            return found
    return None


# ---------------------------------------------------------------------------
# GNU Go — a traditional engine, much weaker than KataGo but installable
# everywhere in seconds (``brew install gnugo``) and usable out of the box.
# It speaks the GTP protocol over a long-lived subprocess.
# ---------------------------------------------------------------------------

class GnuGoEngine:
    """Long-lived ``gnugo --mode gtp`` subprocess used as a fallback engine."""

    def __init__(self, gnugo_path: str, board_size: int = 19) -> None:
        self.gnugo_path = gnugo_path
        self._board_size = board_size
        self._proc: Optional[subprocess.Popen] = None
        self._lock = threading.Lock()

    # -- lifecycle ---------------------------------------------------------

    def start(self, timeout: float = 30.0) -> None:
        self._proc = subprocess.Popen(
            [self.gnugo_path, "--mode", "gtp", "--quiet"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            text=True,
            bufsize=1,
        )
        try:
            name = self._query("name")
        except Exception as exc:  # pragma: no cover - depends on binary
            self.stop()
            raise EngineError(f"gnugo did not answer: {exc}")
        if "gnu go" not in (name or "").lower():
            self.stop()
            raise EngineError(f"unexpected GTP program: {name!r}")

    def stop(self) -> None:
        if self._proc is None:
            return
        try:
            if self._proc.stdin:
                self._proc.stdin.write("quit\n")
                self._proc.stdin.flush()
        except Exception:
            pass
        try:
            self._proc.terminate()
            self._proc.wait(timeout=5)
        except Exception:
            try:
                self._proc.kill()
            except Exception:
                pass
        self._proc = None

    @property
    def running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    # -- GTP plumbing ------------------------------------------------------

    def _query(self, cmd: str) -> str:
        """Send a GTP command and return the body of the response line."""
        assert self._proc and self._proc.stdin and self._proc.stdout
        with self._lock:
            self._proc.stdin.write(cmd + "\n")
            self._proc.stdin.flush()
            while True:
                raw = self._proc.stdout.readline()
                if not raw:  # EOF only (a blank line is "\n", not "")
                    raise EngineError("gnugo closed its stdout")
                line = raw.rstrip("\n")
                if line[:1] in ("=", "?"):
                    body = line[1:].lstrip()
                    # Drop the optional response id (e.g. "=3 ") then the value.
                    body = body.lstrip("0123456789").lstrip()
                    if line[:1] == "?":
                        raise EngineError(f"gnugo error on '{cmd}': {body}")
                    return body

    # -- querying ----------------------------------------------------------

    def analyze(
        self,
        stones: list[tuple[str, str]],
        side_to_move: str,
        komi: float = 7.5,
        rules: str = "chinese",
        board_size: int = 19,
        max_visits: int = 300,
        timeout: float = 30.0,
    ) -> Optional[AnalysisResult]:
        if not self.running:
            raise EngineError("engine is not running")
        # NOTE: every _query() already serialises on self._lock, so we must not
        # take it here too (threading.Lock is not re-entrant -> deadlock).
        self._query(f"boardsize {board_size}")
        self._query(f"komi {komi}")
        self._query("clear_board")
        for color, vertex in stones:
            self._query(f"play {color} {vertex}")
        raw = self._query(f"genmove {side_to_move}").strip()
        move = "pass" if raw.lower() in ("resign", "pass") else raw
        try:
            score = self._query("estimate_score")
        except Exception:
            score = ""
        score_lead = self._parse_score(score, side_to_move)
        suggestion = MoveSuggestion(
            move=move,
            winrate=0.5,
            score_lead=score_lead,
            visits=0,
            prior=0.0,
            pv=[move] if move != "pass" else [],
            order=0,
        )
        return AnalysisResult(
            side_to_move=side_to_move,
            moves=[suggestion],
            root_winrate=0.5,
            root_score_lead=score_lead,
            visits=0,
            elapsed=0.0,
        )

    @staticmethod
    def _parse_score(score: str, side_to_move: str) -> float:
        """Convert a GTP ``estimate_score`` string (e.g. ``W+3.50``) to a
        side-to-move-relative lead in points (positive = good for mover)."""
        s = (score or "").strip()
        if not s or s == "0.00":
            return 0.0
        try:
            if s[0] == "B":
                lead = float(s[1:].lstrip("+"))
            elif s[0] == "W":
                lead = -float(s[1:].lstrip("+"))
            else:
                lead = float(s)
        except (ValueError, IndexError):
            return 0.0
        return lead if side_to_move == "B" else -lead
